Add debug for missing path
Signed-off-by: currantw <taylor.curran@improving.com>

diff --git a/.github/workflows/install-server/action.yml b/.github/workflows/install-server/action.yml
--- a/.github/workflows/install-server/action.yml
+++ b/.github/workflows/install-server/action.yml
@@ -105,3 +105,14 @@ runs:
               make BUILD_TLS=yes
               sudo make install
               echo "export PATH=/usr/local/bin:$PATH" >> ~/.bash_profile
+
+              echo "Valkey installed:"
+              valkey-server --version
+              valkey-cli --version
+
+              # TODO #184: Remove debug
+              if [[ !-e 'valkey/src/valkey-server' || ! -e 'valkey/src/valkey-cli' ]]; then
+                  echo "Valkey binaries not found after build!"
+                  ls -la valkey/src/
+                  exit 1
+              fi
